#!/usr/bin/env bash
WEB_PORT=8080
POSTGRES_PORT=5432
POSTGRES_HOST=ltm-postgres
POSTGRES_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/ltm\?currentSchema=ltm\&autoReconnect=true
PGDATA_LTM=${HOME}/pgdata/ltm
PGDATA=/var/lib/postgresql/data
POSTGRES_PASSWORD=gjhUY876787ytuh87gdf
PROJECT_NAME="ltmdockercompose"
